# SPDX-License-Identifier: Apache-2.0

name: Build, test, and upload PyPI package

on:
    push:
        branches:
            - "main"
            - "release-**"
        tags:
            - "v*"
    pull_request:
        branches:
            - "main"
            - "release-**"
    release:
        types:
            - published

env:
    LC_ALL: en_US.UTF-8

defaults:
    run:
        shell: bash

permissions:
    contents: read

jobs:
    # Create and verify release artifacts
    # - build source dist (tar ball) and wheel
    # - validate artifacts with various tools
    # - upload artifacts to GHA
    build-package:
        name: Build and check packages
        runs-on: ubuntu-latest
        outputs:
            artifact-name: Packages
            dist: dist
            package_name: ${{ steps.metadata.outputs.package_name }}
            package_version: ${{ steps.metadata.outputs.package_version }}
            supported_python_classifiers_json_array: ${{ steps.metadata.outputs.supported_python_classifiers_json_array }}
            supported_python_classifiers_json_job_matrix_value: ${{ steps.metadata.outputs.supported_python_classifiers_json_job_matrix_value }}
        steps:
            - name: "Harden Runner"
              uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
              with:
                  egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs


            - name: "Checkout"
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  # for setuptools-scm
                  fetch-depth: 0

            - name: "Set up Python"
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12.x'

            - name: "Install uv"
              uses: astral-sh/setup-uv@v4

            - name: "Build package"
              run: uv build

            - name: "List build artifacts"
              run: ls -lh dist/

            - name: "Check wheel contents"
              run: uvx check-wheel-contents dist/

            - name: "Check package metadata with twine"
              run: uvx twine check dist/*

            - name: "Extract package metadata"
              id: metadata
              run: |
                  cd dist
                  tar xzf *.tar.gz --wildcards '*/PKG-INFO' --strip-components=1
                  cat PKG-INFO | python - <<'EOF' >> $GITHUB_OUTPUT
                  import email.parser
                  import json, pathlib, re, sys

                  pkg_info = email.parser.Parser().parsestr(sys.stdin.read())

                  version_tokens = []
                  for classifier in pkg_info.get_all("Classifier", []):
                      if match := re.match(r"Programming Language :: Python :: (\d+\.\d+)$", classifier):
                          version_tokens.append(match.group(1))

                  package_name = pkg_info.get("Name")
                  if package_name is None:
                      raise RuntimeError("Package name is not set")

                  package_version = pkg_info.get("Version", "0.0.0")

                  print(f"package_name={package_name}")
                  print(f"package_version={package_version}")
                  print(f"supported_python_classifiers_json_array={json.dumps(version_tokens)}")
                  print(f"""supported_python_classifiers_json_job_matrix_value={json.dumps({"python-version": version_tokens})}""")
                  EOF

            - name: "Generate GitHub summary"
              run: |
                  echo "### Contents of the <code>${{ steps.metadata.outputs.package_name }}</code> package" >> $GITHUB_STEP_SUMMARY
                  echo "" >> $GITHUB_STEP_SUMMARY
                  echo "**Version:** ${{ steps.metadata.outputs.package_version }}" >> $GITHUB_STEP_SUMMARY
                  echo "" >> $GITHUB_STEP_SUMMARY
                  echo "<details><summary>SDist contents</summary>" >> $GITHUB_STEP_SUMMARY
                  echo "" >> $GITHUB_STEP_SUMMARY
                  echo '```' >> $GITHUB_STEP_SUMMARY
                  tar tzf dist/*.tar.gz >> $GITHUB_STEP_SUMMARY
                  echo '```' >> $GITHUB_STEP_SUMMARY
                  echo "</details>" >> $GITHUB_STEP_SUMMARY
                  echo "" >> $GITHUB_STEP_SUMMARY
                  echo "<details><summary>Wheel contents</summary>" >> $GITHUB_STEP_SUMMARY
                  echo "" >> $GITHUB_STEP_SUMMARY
                  echo '```' >> $GITHUB_STEP_SUMMARY
                  unzip -l dist/*.whl >> $GITHUB_STEP_SUMMARY
                  echo '```' >> $GITHUB_STEP_SUMMARY
                  echo "</details>" >> $GITHUB_STEP_SUMMARY
                  echo "" >> $GITHUB_STEP_SUMMARY
                  echo "<details><summary>Package metadata</summary>" >> $GITHUB_STEP_SUMMARY
                  echo "" >> $GITHUB_STEP_SUMMARY
                  echo '```' >> $GITHUB_STEP_SUMMARY
                  cat dist/PKG-INFO >> $GITHUB_STEP_SUMMARY
                  echo '```' >> $GITHUB_STEP_SUMMARY
                  echo "</details>" >> $GITHUB_STEP_SUMMARY

            - name: "Upload build artifacts"
              uses: actions/upload-artifact@ea2feb7fc7a6350c2514f718c4fb78523a8cfe02 # v5.0.0
              with:
                  name: Packages
                  path: dist/*

    # push to Test PyPI on
    # - a new GitHub release is published
    # - a PR is merged into main branch
    publish-test-pypi:
        name: Publish packages to test.pypi.org
        environment: testpypi
        if: ${{ (github.event.action == 'published') || ((github.event_name == 'push') && (github.ref == 'refs/heads/main')) }}
        permissions:
            contents: read
            # see https://docs.pypi.org/trusted-publishers/
            id-token: write
        runs-on: ubuntu-latest
        needs: build-package

        steps:
            - name: "Harden Runner"
              uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
              with:
                  egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

            - name: "Download build artifacts"
              uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
              with:
                  name: Packages
                  path: dist

            - name: "Upload to Test PyPI"
              uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4
              with:
                  repository-url: https://test.pypi.org/legacy/

    # push to Production PyPI on
    # - a new GitHub release is published
    publish-pypi:
        name: Publish release to pypi.org
        environment: pypi
        if: ${{ (github.event.action == 'published') }}
        permissions:
            # see https://docs.pypi.org/trusted-publishers/
            id-token: write
            # allow gh release upload
            contents: write

        runs-on: ubuntu-latest
        needs: build-package

        steps:
            - name: "Harden Runner"
              uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
              with:
                  egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

            - name: "Download build artifacts"
              uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
              with:
                  name: Packages
                  path: dist

            - name: "Sigstore sign package"
              uses: sigstore/gh-action-sigstore-python@f7ad0af51a5648d09a20d00370f0a91c3bdf8f84 # v3.0.1
              with:
                  inputs: |
                      ./dist/*.tar.gz
                      ./dist/*.whl
                  release-signing-artifacts: false

            - name: "Upload artifacts and signatures to GitHub release"
              run: |
                  gh release upload '${{ github.ref_name }}' dist/* --repo '${{ github.repository }}'
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            # PyPI does not accept .sigstore artifacts and
            # gh-action-pypi-publish has no option to ignore them.
            - name: "Remove sigstore signatures before uploading to PyPI"
              run: |
                  rm ./dist/*.sigstore.json

            - name: "Upload to PyPI"
              uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4
